---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: metrics
  namespace: dev
  annotations:
    flux.weave.works/tag.podinfod: glob:*
    flux.weave.works/locked: 'true'
    flux.weave.works/locked_msg: '"Performing risky op"'
    flux.weave.works/locked_user: Ilya Dmitrichenko <ilya@weave.works>
spec:
  replicas: 4
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: metricsd
        image: quay.io/brice/metrics-demo:latest
        # command:
        # # - ./podinfo
        # - --port=3000
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 1
          periodSeconds: 10
          failureThreshold: 2
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"

